const { database } = require('../core/database.js')
const  argv = require('yargs').argv
switch(argv.migration)
{
    case "create":
         database.CreateTable('kelas')
                .Fields('kelas_id')
                    .PrimaryKey()
                    .NotNull()
                .Fields('kode_kelas')
                    .String(9)
                    .Unique()
                    .NotNull()
                .Fields('user_id')
                    .Integer()
                    .NotNull()
                .Fields('nama_kelas')
                    .String(220)
                    .NotNull()
                .Fields('semester')
                    .Integer()
                    .NotNull()
                .Fields('ruangan_id')
                    .Integer()
                    .NotNull()
                .Fields('maksimal_mahasiswa')
                    .Integer()
                    .Null()
                .Fields('jam')
                    .Time()
                    .Null()
                .Fields('hari')
                    .Integer()
                    .NotNull()
                .Fields('is_arsip')
                    .Boolean()
                    .NotNull()
                .ForeignKeys('user_id')
                    .References('users')
                    .OnDeleteCascade()
                .ForeignKeys('ruangan_id')
                    .References('ruangan')
                    .OnDeleteCascade()
                .Timestamp()
                .Execute()
        break;
    case "drop":
        database.DropTable('kelas')
                .Execute()
        break;
}

return
